// This file is generated by /generateSoundsList.js
require('../../../sounds/boom.ogg');
require('../../../sounds/develop.ogg');
require('../../../sounds/fire-heavy.ogg');
require('../../../sounds/hit.ogg');
export default [
    "boom.ogg",
    "develop.ogg",
    "fire-heavy.ogg",
    "hit.ogg"
];